# .github/workflows/build-dist.yml

name: Build and Push Dist

on:
  push:
    branches:
      - main  # or your source branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for pushing later

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or whatever version you use

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npx nx run-many --all --target=build

      - name: Push dist to build branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git checkout --orphan build

          git add .
          git commit -m "Build output from ${GITHUB_SHA}"
          git push --force origin build
